# Конфигурация NFT подарков

# Активные подарки (уже улучшенные)
# Конфигурация NFT подарков

# Активные подарки (уже улучшенные)
NFT_LINKS = {
    49: ["https://t.me/nft/EasterEgg-", 0],
    59: ["https://t.me/nft/CandyCane-", 0],
    51: ["https://t.me/nft/AstralShard-", 0],
    53: ["https://t.me/nft/BDayCandle-", 0],
    55: ["https://t.me/nft/BerryBox-", 0],
    57: ["https://t.me/nft/BunnyMuffin-", 0],
    61: ["https://t.me/nft/CookieHeart-", 0],
    63: ["https://t.me/nft/CrystalBall-", 0],
    65: ["https://t.me/nft/DeskCalendar-", 0],
    67: ["https://t.me/nft/DiamondRing-", 0],
    69: ["https://t.me/nft/DurovsCap-", 0],
    71: ["https://t.me/nft/ElectricSkull-", 0],
    73: ["https://t.me/nft/EternalCandle-", 0],
    75: ["https://t.me/nft/EternalRose-", 0],
    77: ["https://t.me/nft/EvilEye-", 0],
    79: ["https://t.me/nft/FlyingBroom-", 0],
    81: ["https://t.me/nft/GenieLamp-", 0],
    83: ["https://t.me/nft/GingerCookie-", 0],
    85: ["https://t.me/nft/HangingStar-", 0],
    87: ["https://t.me/nft/HexPot-", 0],
    89: ["https://t.me/nft/HomemadeCake-", 0],
    91: ["https://t.me/nft/HypnoLollipop-", 0],
    93: ["https://t.me/nft/IonGem-", 0],
    95: ["https://t.me/nft/JackInTheBox-", 0],
    97: ["https://t.me/nft/JellyBunny-", 0],
    99: ["https://t.me/nft/JesterHat-", 0],
    101: ["https://t.me/nft/JingleBells-", 0],
    103: ["https://t.me/nft/KissedFrog-", 0],
    105: ["https://t.me/nft/LolPop-", 0],
    107: ["https://t.me/nft/LootBag-", 0],
    255: ["https://t.me/nft/LoveCandle-", 0],
    109: ["https://t.me/nft/LovePotion-", 0],
    111: ["https://t.me/nft/LunarSnake-", 0],
    113: ["https://t.me/nft/MadPumpkin-", 0],
    115: ["https://t.me/nft/MagicPotion-", 0],
    117: ["https://t.me/nft/MiniOscar-", 0],
    119: ["https://t.me/nft/NekoHelmet-", 0],
    121: ["https://t.me/nft/PartySparkler-", 0],
    123: ["https://t.me/nft/PerfumeBottle-", 0],
    125: ["https://t.me/nft/PlushPepe-", 0],
    127: ["https://t.me/nft/PreciousPeach-", 0],
    129: ["https://t.me/nft/RecordPlayer-", 0],
    131: ["https://t.me/nft/SakuraFlower-", 0],
    133: ["https://t.me/nft/SantaHat-", 0],
    135: ["https://t.me/nft/ScaredCat-", 0],
    137: ["https://t.me/nft/SharpTongue-", 0],
    139: ["https://t.me/nft/SignetRing-", 0],
    141: ["https://t.me/nft/SkullFlower-", 0],
    144: ["https://t.me/nft/SleighBell-", 0],
    146: ["https://t.me/nft/SnowGlobe-", 0],
    148: ["https://t.me/nft/SnowMittens-", 0],
    151: ["https://t.me/nft/SpicedWine-", 0],
    45:  ["https://t.me/nft/SpyAgaric-", 0],
    153: ["https://t.me/nft/StarNotepad-", 0],
    46:  ["https://t.me/nft/SwissWatch-", 0],
    155: ["https://t.me/nft/TamaGadget-", 0],
    157: ["https://t.me/nft/TopHat-", 0],
    159: ["https://t.me/nft/ToyBear-", 0],
    161: ["https://t.me/nft/TrappedHeart-", 0],
    163: ["https://t.me/nft/VintageCigar-", 0],
    165: ["https://t.me/nft/VoodooDoll-", 0],
    167: ["https://t.me/nft/WinterWreath-", 0],
    169: ["https://t.me/nft/WitchHat-", 0],
    171: ["https://t.me/nft/ArtisanBrick-", 0],
    173: ["https://t.me/nft/BigYear-", 0],
    175: ["https://t.me/nft/BondedRing-", 0],
    177: ["https://t.me/nft/BowTie-", 0],
    179: ["https://t.me/nft/CloverPin-", 0],
    181: ["https://t.me/nft/CupidCharm-", 0],
    183: ["https://t.me/nft/FaithAmulet-", 0],
    185: ["https://t.me/nft/FreshSocks-", 0],
    187: ["https://t.me/nft/GemSignet-", 0],
    189: ["https://t.me/nft/HappyBrownie-", 0],
    191: ["https://t.me/nft/HeartLocket-", 0],
    193: ["https://t.me/nft/HeroicHelmet-", 0],
    195: ["https://t.me/nft/HolidayDrink-", 0],
    197: ["https://t.me/nft/IceCream-", 0],
    199: ["https://t.me/nft/InputKey-", 0],
    201: ["https://t.me/nft/InstantRamen-", 0],
    203: ["https://t.me/nft/IonicDryer-", 0],
    205: ["https://t.me/nft/JollyChimp-", 0],
    207: ["https://t.me/nft/JoyfulBundle-", 0],
    209: ["https://t.me/nft/LightSword-", 0],
    211: ["https://t.me/nft/LowRider-", 0],
    213: ["https://t.me/nft/LushBouquet-", 0],
    215: ["https://t.me/nft/MightyArm-", 0],
    217: ["https://t.me/nft/MoonPendant-", 0],
    219: ["https://t.me/nft/MousseCake-", 0],
    221: ["https://t.me/nft/NailBracelet-", 0],
    223: ["https://t.me/nft/PetSnake-", 0],
    225: ["https://t.me/nft/RestlessBar-", 0],
    227: ["https://t.me/nft/SkyStilettos-", 0],
    229: ["https://t.me/nft/SnakeBox-", 0],
    231: ["https://t.me/nft/SnoopCigar-", 0],
    233: ["https://t.me/nft/SnoopDogg-", 0],
    235: ["https://t.me/nft/SpringBasket-", 0],
    237: ["https://t.me/nft/StellarRocket-", 0],
    239: ["https://t.me/nft/SwagBag-", 0],
    241: ["https://t.me/nft/ValentineBox-", 0],
    243: ["https://t.me/nft/WestsideSign-", 0],
    245: ["https://t.me/nft/WhipCupcake-", 0],
    247: ["https://t.me/nft/XmasStocking-", 0],
    249: ["https://t.me/nft/MoneyPot-", 0],
    251: ["https://t.me/nft/BlingBinky-", 0],
    253: ["https://t.me/nft/PrettyPosy-", 0],
    257: ["https://t.me/nft/VictoryMedal-", 0],
    258: ["https://t.me/nft/UFSStrike-", 0],
    # New gifts from the list (non‑pre‑market)
    259: ["https://t.me/nft/1-may-", 0],
    260: ["https://t.me/nft/backpack-", 0],
    261: ["https://t.me/nft/book-", 0],
    262: ["https://t.me/nft/candle-lamp-", 0],
    263: ["https://t.me/nft/case-", 0],
    264: ["https://t.me/nft/christmas-tree-", 0],
    265: ["https://t.me/nft/coffin-", 0],
    266: ["https://t.me/nft/easter-cake-", 0],
    267: ["https://t.me/nft/gravestone-", 0],
    268: ["https://t.me/nft/ice-cream-scoops-", 0],
    269: ["https://t.me/nft/papakha-", 0],          # Khabib's Papakha
    270: ["https://t.me/nft/kitty-medallion-", 0],
    271: ["https://t.me/nft/mask-", 0],
    272: ["https://t.me/nft/bear-new-year-", 0],    # New Year's Bear
    273: ["https://t.me/nft/pen-", 0],
    274: ["https://t.me/nft/pink-flamingo-", 0],
    275: ["https://t.me/nft/rare-bird-", 0],
    276: ["https://t.me/nft/resistance-dog-", 0],
    277: ["https://t.me/nft/roses-", 0],
    278: ["https://t.me/nft/sandcastle-", 0],
    279: ["https://t.me/nft/statue-of-liberty-", 0],
    280: ["https://t.me/nft/surfboard-", 0],
    281: ["https://t.me/nft/plane-", 0],             # Telegram Pin
    282: ["https://t.me/nft/torch-freedom-", 0],
    283: ["https://t.me/nft/trojan-horse-", 0],
}

# Подарки в премаркете (Ton Pre-market)
PROMARKET_LINKS = {
    "B-day Candle": "bday-candle",
    "Candy Cane": "candy-cane",
    "Diamond Ring": "diamond-ring",
    "Durov's Cap": "durovs-cap",
    "Ginger Cookie": "ginger-cookie",
    "Ice Cream": "ice-cream",
    "Kissed Frog": "kissed-frog",
    "Magic Potion": "magic-potion",
    "Party Sparkler": "party-sparkler",
    "Pet Snake": "pet-snake",
    "Record Player": "record-player",
    "Sakura Flower": "sakura-flower",
    "Star Notepad": "star-notepad",
    "Top Hat": "top-hat",
    "Trapped Heart": "trapped-heart",
    "Bonded Ring": "bonded-ring",
    "Clover Pin": "clover-pin",
    "Dove of Peace": "dove-peace",
    "Durov's Boots": "durovs-boots",
    "Durov's Coat": "durovs-coat",
    "Durov's Figurine": "durovs-figurine",
    "Durov's Sunglasses": "durovs-sunglasses",
    "Ice Cream Cone": "ice-cream-cone",
    "Bunny Muffin": "bunny-muffin",
    "Red Star": "red-star",
    "Tama Gadget": "tama-gadget",
    "Stellar Rocket": "stellar-rocket",
    "Restless Jar": "restless-jar",
    "Coconut": "coconut",
}

# Маппинг имен подарков для парсинга цен (добавлены новые)
GIFT_NAME_MAPPING = {
    '1 May': '1-may',
    'Artisan Brick': 'brick',
    'Astral Shard': 'astral-shard',
    'B-day Candle': 'bday-candle',
    'Backpack': 'backpack',
    'Berry Box': 'berry-box',
    'Big Year': 'big-year',
    'Bling Binky': 'gold-nipples',
    'Bonded Ring': 'bonded-ring',
    'Book': 'book',
    'Bow Tie': 'bow-tie',
    'Bunny Muffin': 'bunny-muffin',
    'Candle Lamp': 'candle-lamp',
    'Candy Cane': 'candy-cane',
    'Case': 'case',
    'Christmas Tree': 'christmas-tree',
    'Clover Pin': 'clover',
    'Coconut': 'coconut',
    'Coffin': 'coffin',
    'Cookie Heart': 'cookie-heart',
    'Crystal Ball': 'crystal-ball',
    'Crystal Eagle': 'crystal-eagle',
    'Cupid Charm': 'cupid-charm',
    'Desk Calendar': 'desk-calendar',
    'Diamond Ring': 'diamond-ring',
    'Dove of Peace': 'dove-peace',
    'Durov\'s Boots': 'durovs-boots',
    'Durov\'s Cap': 'durovs-cap',
    'Durov\'s Coat': 'durovs-coat',
    'Durov\'s Figurine': 'durovs-figurine',
    'Durov\'s Sunglasses': 'durovs-sunglasses',
    'Easter Cake': 'easter-cake',
    'Easter Egg': 'easter-egg',
    'Electric Skull': 'electric-skull',
    'Eternal Candle': 'eternal-candle',
    'Eternal Rose': 'eternal-rose',
    'Evil Eye': 'evil-eye',
    'Faith Amulet': 'mosque',
    'Flying Broom': 'flying-broom',
    'Fresh Socks': 'socks',
    'Gem Signet': 'gem-signet',
    'Genie Lamp': 'genie-lamp',
    'Ginger Cookie': 'ginger-cookie',
    'Gravestone': 'gravestone',
    'Hanging Star': 'hanging-star',
    'Happy Brownie': 'poop',
    'Heart Locket': 'heart-locket',
    'Heroic Helmet': 'heroic-helmet',
    'Hex Pot': 'hex-pot',
    'Holiday Drink': 'holiday-drink',
    'Homemade Cake': 'homemade-cake',
    'Hypno Lollipop': 'hypno-lollipop',
    'Ice Cream': 'ice-cream-bar',
    'Ice Cream Cone': 'ice-cream-cone',
    'Ice Cream Scoops': 'ice-cream-scoops',
    'Input Key': 'heart-button',
    'Instant Ramen': 'instant-noodles',
    'Ion Gem': 'ion-gem',
    'Ionic Dryer': 'ionic-dryer',
    'Jack in the Box': 'jackinthebox',
    'Jelly Bunny': 'jelly-bunny',
    'Jester Hat': 'jester-hat',
    'Jingle Bells': 'jingle-bells',
    'Jolly Chimp': 'jolly-chimp',
    'Joyful Bundle': 'joyful-bundle',
    'Khabib\'s Papakha': 'papakha',
    'Kissed Frog': 'kissed-frog',
    'Kitty Medallion': 'kitty-medallion',
    'Light Sword': 'light-sword',
    'Lol Pop': 'lolpop',
    'Loot Bag': 'loot-bag',
    'Love Candle': 'love-candle',
    'Love Potion': 'love-potion',
    'Low Rider': 'low-rider',
    'Lunar Snake': 'lunar-snake',
    'Lush Bouquet': 'lush-bouquet',
    'Mad Pumpkin': 'mad-pumpkin',
    'Magic Potion': 'magic-potion',
    'Mask': 'mask',
    'Mighty Arm': 'golden-biceps',
    'Mini Oscar': 'mini-oscar',
    'Money Pot': 'gold-pot',
    'Moon Pendant': 'moon-pendant',
    'Mousse Cake': 'cherry-cake',
    'Nail Bracelet': 'nail-bracelet',
    'Neko Helmet': 'neko-helmet',
    'New Year\'s Bear': 'bear-new-year',
    'Party Sparkler': 'party-sparkler',
    'Pen': 'pen',
    'Perfume Bottle': 'perfume-bottle',
    'Pet Snake': 'pet-snake',
    'Pink Flamingo': 'pink-flamingo',
    'Plush Pepe': 'plush-pepe',
    'Precious Peach': 'precious-peach',
    'Pretty Posy': 'money-bouquet',
    'Rare Bird': 'rare-bird',
    'Record Player': 'record-player',
    'Red Star': 'red-star',
    'Resistance Dog': 'resistance-dog',
    'Restless Jar': 'restless-jar',
    'Roses': 'roses',
    'Sakura Flower': 'sakura-flower',
    'Sandcastle': 'sandcastle',
    'Santa Hat': 'santa-hat',
    'Scared Cat': 'scared-cat',
    'Sharp Tongue': 'sharp-tongue',
    'Signet Ring': 'signet-ring',
    'Skull Flower': 'skull-flower',
    'Sky Stilettos': 'heels',
    'Sleigh Bell': 'sleigh-bell',
    'Snake Box': 'snake-box',
    'Snoop Cigar': 'snoop-cigar',
    'Snoop Dogg': 'snoop-dogg',
    'Snow Globe': 'snow-globe',
    'Snow Mittens': 'snow-mittens',
    'Spiced Wine': 'spiced-wine',
    'Spring Basket': 'easter-backet',
    'Spy Agaric': 'spy-agaric',
    'Star Notepad': 'star-notepad',
    'Statue of Liberty': 'statue-of-liberty',
    'Stellar Rocket': 'stellar-rocket',
    'Surfboard': 'surfboard',
    'Swag Bag': 'swag-bag',
    'Swiss Watch': 'swiss-watch',
    'Tama Gadget': 'tama-gadget',
    'Telegram Pin': 'plane',
    'Top Hat': 'top-hat',
    'Torch of Freedom': 'torch-freedom',
    'Toy Bear': 'toy-bear',
    'Trapped Heart': 'trapped-heart',
    'Trojan Horse': 'trojan-horse',
    'UFC Strike': 'ufc-mystery-box',
    'Valentine Box': 'valentine-box',
    'Victory Medal': 'medal',
    'Vintage Cigar': 'vintage-sigar',
    'Voodoo Doll': 'voodoo-doll',
    'Westside Sign': 'westside-sign',
    'Whip Cupcake': 'whip-cupcake',
    'Winter Wreath': 'winter-wreath',
    'Witch Hat': 'witch-hat',
    'Xmas Stocking': 'xmas-stocking',
}